package com.catus.backend.model;

/**
 * Diary generation type indicating how the diary was created.
 */
public enum DiaryGenerationType {
    /**
     * Automatically generated by scheduled job at midnight
     */
    AUTO,

    /**
     * Manually triggered by user
     */
    MANUAL
}
